packages:
  - apps/*
  - packages/*

savePrefix: ''
nodeVersion: 24.18.0
engineStrict: true
strictDepBuilds: true
dangerouslyAllowAllBuilds: false
blockExoticSubdeps: true
allowBuilds:
  esbuild: true
